name: "Check PR content"
on:
  pull_request:
    types:
      [opened, edited, assigned, closed, synchronize, review_requested, ready_for_review]

jobs:
  check_pr:
    runs-on: ubuntu-latest
    steps:
    - name: Check PR
      uses: JJ/github-pr-contains-action@releases/v14.1.1
      with:
        github-token: ${{ github.token }}
        bodyContains: 'a'

    - run: echo ok bro idk
